### ISSUE TITLE
On Fast doc for stage peering one step is missing

### ISSUE THREAD

**Issue by tamasszebeni** [GoogleCloudPlatform/cloud-foundation-fabric#1100]
In stage 'network peering' the documentation misses to mention the need to copy the tfvars file over, symptom is that security stage related provider file is not created if output location is set in tfvars file as that info is not passed from auto global tfvars.
Other network related doc page like separated envs mention it properly
```
cp ../00-bootstrap/terraform.tfvars .
```

**Comment by ludoo** [comment]
Thanks for raising this. The user-defined tfvars file should not in fact be copied, since relevant values are already set in the generated globals tfvars and stage tfvars should be specific to the variable of each stage.

The only one missing there is the one you flagged, that controls output files generation and it's missing intentionally: output files are a per-stage decision, since they are not needed (and potentially problematic) when implementing CI/CD.

But I agree that we should be explicit about the need to set `output_file` variable in every stage.
