### ISSUE TITLE
possible to use modules/iam-service-account with WIF AWS provider

### ISSUE THREAD

**Issue by kthhrv** [GoogleCloudPlatform/cloud-foundation-fabric#1529]
I want to allow some automation in AWS to write to the composer dag bucket

digging through the fast stages and blueprints I'm not clear how to connect the SA to the WIF pool

is it possible using the `modules/iam-service-account ` module? thanks

if it is supported and I work it out how to use it, I'll add to the module README

I'm testing this in a sandbox GCP Org

```
module "data-platform" {
  source          = "git@github.com:timeoutdigital/platform-gcp-cff.git//blueprints/data-solutions/data-platform-minimal?ref=production"
......

module "aws-cpl-sa" {
  source       = "git@github.com:timeoutdigital/platform-gcp-cff.git//modules/iam-service-account"
  project_id   = module.data-platform.projects.project_id.processing
  prefix       = var.prefix
  name         = "prc-aws-0"
  display_name = "SA used by AWS CPLs"
  iam = {
    "roles/iam.workloadIdentityUser" = [
      (google_iam_workload_identity_pool_provider.default.workload_identity_pool_provider_id)
    ]
  }
  iam_storage_roles = {
    europe-west1-tosbx-dev-dt-p-34cfd062-bucket = ["roles/storage.objectAdmin"]
  }
}

resource "google_iam_workload_identity_pool" "default" {
  provider                  = google-beta
  project                   = module.data-platform.projects.project_id.processing
  workload_identity_pool_id = "${var.prefix}-dev-dp-wip"
}

resource "google_iam_workload_identity_pool_provider" "default" {
  provider = google-beta
  project  = module.data-platform.projects.project_id.processing
  workload_identity_pool_id = (
    google_iam_workload_identity_pool.default.workload_identity_pool_id
  )
  workload_identity_pool_provider_id = "${var.prefix}-dev-dp-wipp"
  aws {
    account_id = "****************"
  }
}
```
```
$ tf apply
...
╷
│ Error: invalid value for members.0 (IAM members must have one of the values outlined here: https://cloud.google.com/billing/docs/reference/rest/v1/Policy#Binding)
│ 
│   with module.aws-cpl-sa.google_service_account_iam_binding.roles["roles/iam.workloadIdentityUser"],
│   on .terraform/modules/aws-cpl-sa/modules/iam-service-account/iam.tf line 84, in resource "google_service_account_iam_binding" "roles":
│   84:   members            = each.value
│ 
╵
```

**Comment by ludoo** [comment]
Hey Keith, to allow exchanging external credentials via the pool you need to assign a specific role to the right principal on the service account. One example in FAST is [here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/0-bootstrap/cicd.tf#L107), but it needs some interpolating:

- the role you need to assign is `roles/iam.workloadIdentityUser`
- the principal is prefixed with `principal://` or `principalSet://` and contains an id that maps to the pool, and the attributes in the exchanged tokens

So you need to

- set up mappings in your provider (e.g. by following [the documentation](https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#mappings-and-conditions))
- figure out what value the attributes in your external tokens will have and build the right principal string

If the `sub` in the originating token is not too granular just use that:

`principal://iam.googleapis.com/projects/[PROJECT_NUMBER]/locations/global/workloadIdentityPools/[POOL_ID]/subject/[SUBJECT]`

otherwise build a condition using mapped attributes:

`principalSet://iam.googleapis.com/projects/[PROJECT_NUMBER]/locations/global/workloadIdentityPools/[POOL_ID]/attribute.aws_role/[ROLE_NAME]` or somesuch

**Comment by kthhrv** [comment]
I managed to set it manually in the web console first, now trying to do it with terraform

I think my question here is what should the structure of the `iam` block in the modules/iam-service-account be, I've not managed to find a documented example the one in FAST is for git* and the code is quite complex (for a newbie)

```
iam = {
    "roles/iam.workloadIdentityUser" = [
     ???
    ]
  }
```
this is where the SA is connected to the pool/provider correct?

**Comment by ludoo** [comment]
add the correct principal where you have the question marks :)

**Comment by kthhrv** [comment]
Thanks, simple once you understand ;)
