### ISSUE TITLE
how can we set hostname using google compute instance template using MIG?

### ISSUE THREAD

**Issue by rahulguptaft9** [GoogleCloudPlatform/cloud-foundation-fabric#1660]
While creating a vm instance as stand alone it shows an option of hostname which works and it can be shown after the vm instance is up and running. But when we try to do the same using the template hostname value shows null.

**Comment by ludoo** [comment]
I don't think you can set hostname on a template. Closing this, feel free to reopen if you find documented proof it can be done.

**Comment by rahulguptaft9** [comment]
> I don't think you can set hostname on a template. Closing this, feel free to reopen if you find documented proof it can be done.

But there is an option of using hostname while creating a template in the UI of GCP is it futile or working?

**Comment by ludoo** [comment]
I don't see hostname in the GCE API Template object...

**Comment by rahulguptaft9** [comment]
![template_hostname](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/93612063/20e0b6d0-cd41-4e38-8167-bb75ddff96bf)

![vm_hostname](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/93612063/771743a6-255f-4130-8371-09d749a12b8c)


See the above two images 1) entering hostname in vm instance template(which does not work)

2) entering hostname in vm instance(which works)

what can be the reason? since there is an input value to enter hostname in the vm instance template

**Comment by ludoo** [comment]
I believe you, but the console is immaterial for Terraform.

If the field is not exposed in the API and the resource, there's nothing that can be implemented

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template

**Comment by rahulguptaft9** [comment]
Can you please expose it in the API? xD

**Comment by ludoo** [comment]
Ahah, I wish...

**Comment by rahulguptaft9** [comment]
Ok so off topic!! can you please give your inputs for the below issue as well?

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/1657
Depends_on or time_sleep not working #1657 

I am actually trying to register the dns of my VMs which are getting provisioned through MIG(google_instance_template and resource manager) for I am using fabric module. But when I use terraform apply it throws me the below error

Error: Invalid for_each argument
│
│   on .terraform\modules\private-dns\modules\dns\main.tf line 165, in resource "google_dns_record_set" "dns_record_set": 
│  165:   for_each     = local.recordsets
│     ├────────────────
│     │ local.recordsets will be known only after apply
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so
│ Terraform cannot determine the full set of keys that will identify the instances of this resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and   
│ place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value      
│ depends on, and then apply a second time to fully converge.
But to bypass it, I am using depends on dns module which first provisions the vms and then on the basis of ip addresses it registers the DNS. Please help me why is depends_on or time_sleep not working?

resource "time_sleep" "wait_for_workflow_mig" {
  depends_on = [module.workflow-mig-resource-manager]

  create_duration = "5m"  # Adjust the duration as needed (e.g., 5 minutes)
}
depends_on = [time_sleep.wait_for_workflow_mig]

**Comment by juliocc** [comment]
Please don't cross post unrelated issues. I already replied to that one in #1657

**Comment by olliefr** [comment]
The Cloud Console ("the UI") is misleading you, @rahulguptaft9. An instance template does not have a `hostname` property. You can see it for yourself in the Compute Engine API docs: [`instanceTemplate`](https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates). 

You can also verify this by creating an instance template with the hostname of your choice in the Cloud Console. Fill out the fields that you need, including the **Hostname** but before you click the **Create** button, check out the **Equivalent Command Line** or the **Equivalent REST** option. You will see that there is no mention of the hostname in the actual request that Cloud Console sends to the API. So while there is a **Hostname** field on the form, it is not being used. I'd say it's a bug in the UI. They probably reuse the same form that is being used to create a new VM instance.

If you proceed and create the instance template and then try to create a VM instance with that template using Cloud Console, you will see that the **Hostname** field is not populated but you can provide a value at that point. Before you click **Create** on that form, though, check out the **EQUIVALENT CODE** section where you can see the REST request that the form is going to send. You will notice that there is a `hostname` field in the request. The Compute Engine API resource [`Instance`](https://cloud.google.com/compute/docs/reference/rest/v1/instances) docs confirm that such field is supported.

I think this makes sense &ndash; all hostnames are unique, so each VM is going to have its own. An instance template could not have had a `hostname` field because then it would be limited to creating a single instance. Instead, the instance template allows you to define the properties shared by all the VMs created using that template and it leaves it to you to define the unique properties when you create instances using the template. You can also selectively *override* the values defined in the instance template when you create a new VM instance with that template.

To implement this in Terraform: 

1. Create your instance template using the [`google_compute_instance_template`](google_compute_instance_template) resource. 
2. Create VM instances from that template using the [`google_compute_instance_from_template`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_from_template) resource. 
 
The key thing here is that in **Step 2** you can use the `hostname` argument to provide a hostname for this VM. You can also override other parameters set in the template, if you wish.

```hcl
resource "google_compute_instance_template" "mytemplate" {
  # ...
}

resource "google_compute_instance_from_template" "myvm" {
  # ...
  source_instance_template = google_compute_instance_template.mytemplate.self_link_unique

  # Override fields from instance template
  hostname = "vm-1.example.com"
  # ...
}
```

You can see the full list of arguments that you can override in the [`google_compute_instance`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#attributes-reference) resource docs.

I hope this helps!

**Comment by olliefr** [comment]
Also, please note that custom hostnames are not resolved by internal DNS so you will need to create a corresponding DNS record in the appropriate zone yourself. For more information, see [create a VM instance with a custom hostname](https://cloud.google.com/compute/docs/instances/custom-hostname-vm).
