### ISSUE TITLE
Compute VM, tag_bindings don't work

### ISSUE THREAD

**Issue by hoppefamily** [GoogleCloudPlatform/cloud-foundation-fabric#1763]
The implementation of setting secure tags on a VM instance in module compute_vm in tags.tf is not right.

There two ways:
A: Use of "google_tags_location_tag_binding" instead of "google_tags_tag_binding". Requires also a project_number variable.
B: Delete tags.tf and add this to main.tf 
params {
    resource_manager_tags = var.tag_bindings
  }

I am not sure what of this two is the right way.

**Comment by ludoo** [comment]
You are correct, and sorry for delaying a proper answer. I will send a PR to fix this between today and tomorrow.

**Comment by ludoo** [comment]
Digging a bit deeper into this, I think we should support both methods:

- `params.resource_manager_tags` and `boot_disk.initialize_params.resource_manager_tags` are destructive, changing the bindings will recreate the resources but they are a simple way of setting tag bindings
- `google_tags_location_tag_binding` works for both instance and disk resources, and as you write it's a simple matter of changing the resource type and adding the `location` attribute; implementing it for disks will be a bit more challenging though

I'll prepare a PR for the second option, and look into how best to add the second in the same PR, or in a subsequent one.

Thanks for raising this.

**Comment by ludoo** [comment]
Well, turns out there's a permadiff in the provider unless the project number is used, which would force us to use a data source in the VM module, which we will never want to have:

![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/66007/f250aa19-fa51-4f4f-854d-849679f2b747)

I'm sending the PR eventually, but this also needs fixing in the provider.
