### ISSUE TITLE
Publish modules to Terraform registry?

### ISSUE THREAD

**Issue by nika-pr** [GoogleCloudPlatform/cloud-foundation-fabric#2428]
Is there a specific reason why the cloud-foundation-fabic modules cannot be published to the Terraform registry like the terraform-google-modules are published?

https://registry.terraform.io/search/modules?namespace=terraform-google-modules

**Comment by ludoo** [comment]
We don't see a real benefit of doing it, especially since a) we have a monorepo, and b) they can already be consumed via git sources with versioning.

Closing this, feel free to reopen as a discussion if you want to provide more points of view on the topic. :)

**Comment by ludoo** [comment]
What most of my customers do is having a dedicated repo just for modules, with tag-based versions, and then tack `&depth=1` to the source URL to limit depth of what is fetched.

**Comment by nika-pr** [comment]
I saw the note in one of the readmes that the modules are intended as being copied to your own repo - I find that approach rather ugly if I want to keep up with upstream changes of this repo.

Also depth will only limit git history fetched, not total directories - there's no way to use the cloud-foundation-fabric modules with the GitHub source that does not also fetch all the other directories like blueprints.

Publishing to the Terraform registry would certainly solve our usage issues the most straightforward way right now.

**Comment by ludoo** [comment]
Ok, let's reopen this and take it into consideration, it's the first time in 6 years we heard it so strongly so we need to sit and look at how much effort would be required to set it up and maintain this.

**Comment by juliocc** [comment]
@nika-pr We've looked into publishing Fabric modules directly to the Terraform Registry.  While technically feasible, the current structure of our repo means we can only publish everything as a single registry module (with submodules for individual Fabric modules). This wouldn't address the storage concern you raised, as it would still download the entire repository, including files unrelated to the modules themselves.

Ideally, we'd have separate repositories for each module, but this isn't currently possible due to resource constraints.
