### ISSUE TITLE
VPC network policies terraform issue 

### ISSUE THREAD

**Issue by rafstef** [GoogleCloudPlatform/cloud-foundation-fabric#713]
Hi, after the deploy of 02-networking-nva and 02-networking-security I deployed 2 different projects using 03-project-factories.

I shared the network of my spoke VPC with the target project and I gave the network access to my project user group using the yaml template of the 03-project-factories data folder.

When I go to deploy a new network inside my spoke vpc using 02-networking-nva stack, terraform delete the policies that the project factories create on the existing projects because these configuration will be read as outside terraform config.

Are there any workaround to don't lose the existing network group policies? Maybe I am wrong using the modules ?

Best

**Comment by sruffilli** [comment]
Hey rafstef, thank you for the feedback.
Can you provide the instructions to repro this on our side, including the configuration of the VPC you're adding and the policies you've added through the project factory. Thanks!

**Comment by ludoo** [comment]
After discussing and a second user report for the same thing, this is due to the VPC module's subnet factory always setting a binding for `compute.networkUser` even when no members have been specified. The code [is here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/subnets.tf#L28).
